version: '3.8'

services:
  productdb:
    container_name: productdb
    image: postgres:latest
    ports:
      - 15100:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product
  orderdb:
    container_name: orderdb
    image: postgres:latest
    ports:
      - 15101:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=order      