version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  productdb:
    container_name: productdb
    image: postgres:latest
    ports:
      - 15100:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product
  orderdb:
    container_name: orderdb
    image: postgres:latest
    ports:
      - 15101:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=order   
  cartdb:
    container_name: cartdb
    image: postgres:latest
    ports:
      - 15102:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cart 
  userdb:
    container_name: userdb
    image: postgres:latest
    ports:
      - 15103:5432
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user
  ratingdb:
    container_name: ratingdb
    image: postgres:latest
    ports:
      - 15104:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rating
       